-- Compiled from colors/seruzen_src.lua — do not edit manually.
-- Regenerate with :SeruzenCompile

vim.g.colors_name = "seruzen"

vim.api.nvim_set_hl(0, "@attribute", { link = "PreProc" })
vim.api.nvim_set_hl(0, "@boolean", { link = "Boolean" })
vim.api.nvim_set_hl(0, "@character", { link = "Constant" })
vim.api.nvim_set_hl(0, "@character.special", { link = "Special" })
vim.api.nvim_set_hl(0, "@comment", { link = "Comment" })
vim.api.nvim_set_hl(0, "@comment.documentation", { link = "@comment" })
vim.api.nvim_set_hl(0, "@comment.error", { link = "Error" })
vim.api.nvim_set_hl(0, "@comment.note", { link = "DiagnosticInfo" })
vim.api.nvim_set_hl(0, "@comment.todo", { link = "Todo" })
vim.api.nvim_set_hl(0, "@comment.warning", { link = "WarningMsg" })
vim.api.nvim_set_hl(0, "@constant", { bold = true, fg = "#84715F" })
vim.api.nvim_set_hl(0, "@constant.builtin", { link = "Constant" })
vim.api.nvim_set_hl(0, "@constant.macro", { link = "Constant" })
vim.api.nvim_set_hl(0, "@constructor", { link = "Special" })
vim.api.nvim_set_hl(0, "@constructor.lua", { link = "Delimiter" })
vim.api.nvim_set_hl(0, "@diff.delta", { link = "DiffChange" })
vim.api.nvim_set_hl(0, "@diff.minus", { link = "DiffDelete" })
vim.api.nvim_set_hl(0, "@diff.plus", { link = "DiffAdd" })
vim.api.nvim_set_hl(0, "@function", { link = "Function" })
vim.api.nvim_set_hl(0, "@function.builtin", { link = "Special" })
vim.api.nvim_set_hl(0, "@function.call", { link = "@function" })
vim.api.nvim_set_hl(0, "@function.macro", { link = "PreProc" })
vim.api.nvim_set_hl(0, "@function.method", { link = "@function" })
vim.api.nvim_set_hl(0, "@function.method.call", { link = "@function" })
vim.api.nvim_set_hl(0, "@keyword.conditional", { link = "Statement" })
vim.api.nvim_set_hl(0, "@keyword.conditional.ternary", { link = "@keyword.conditional" })
vim.api.nvim_set_hl(0, "@keyword.coroutine", { link = "Statement" })
vim.api.nvim_set_hl(0, "@keyword.debug", { link = "Special" })
vim.api.nvim_set_hl(0, "@keyword.directive", { link = "PreProc" })
vim.api.nvim_set_hl(0, "@keyword.directive.define", { link = "@keyword.directive" })
vim.api.nvim_set_hl(0, "@keyword.exception", { link = "Statement" })
vim.api.nvim_set_hl(0, "@keyword.function", { link = "Statement" })
vim.api.nvim_set_hl(0, "@keyword.import", { link = "PreProc" })
vim.api.nvim_set_hl(0, "@keyword.operator", { link = "Statement" })
vim.api.nvim_set_hl(0, "@keyword.repeat", { link = "Statement" })
vim.api.nvim_set_hl(0, "@keyword.return", { link = "Statement" })
vim.api.nvim_set_hl(0, "@keyword.storage", { link = "Type" })
vim.api.nvim_set_hl(0, "@label", { link = "Statement" })
vim.api.nvim_set_hl(0, "@label.vimdoc", { bold = true, fg = "#695645" })
vim.api.nvim_set_hl(0, "@lsp.type.boolean", { link = "@boolean" })
vim.api.nvim_set_hl(0, "@lsp.type.builtinType", { link = "@type.builtin" })
vim.api.nvim_set_hl(0, "@lsp.type.comment", { link = "@comment" })
vim.api.nvim_set_hl(0, "@lsp.type.decorator", { link = "@attribute" })
vim.api.nvim_set_hl(0, "@lsp.type.deriveHelper", { link = "@attribute" })
vim.api.nvim_set_hl(0, "@lsp.type.enum", { link = "@type" })
vim.api.nvim_set_hl(0, "@lsp.type.enumMember", { link = "@constant" })
vim.api.nvim_set_hl(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
vim.api.nvim_set_hl(0, "@lsp.type.formatSpecifier", { link = "@markup.list" })
vim.api.nvim_set_hl(0, "@lsp.type.generic", { link = "@variable" })
vim.api.nvim_set_hl(0, "@lsp.type.interface", { link = "@type" })
vim.api.nvim_set_hl(0, "@lsp.type.keyword", { link = "Statement" })
vim.api.nvim_set_hl(0, "@lsp.type.lifetime", { link = "@keyword.storage" })
vim.api.nvim_set_hl(0, "@lsp.type.namespace", { link = "@module" })
vim.api.nvim_set_hl(0, "@lsp.type.number", { link = "@number" })
vim.api.nvim_set_hl(0, "@lsp.type.operator", { link = "@operator" })
vim.api.nvim_set_hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
vim.api.nvim_set_hl(0, "@lsp.type.property", { link = "@property" })
vim.api.nvim_set_hl(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
vim.api.nvim_set_hl(0, "@lsp.type.selfTypeKeyword", { link = "@variable.builtin" })
vim.api.nvim_set_hl(0, "@lsp.type.string", { link = "@string" })
vim.api.nvim_set_hl(0, "@lsp.type.typeAlias", { link = "@type.definition" })
vim.api.nvim_set_hl(0, "@lsp.type.unresolvedReference", { sp = "#C65333", undercurl = true })
vim.api.nvim_set_hl(0, "@lsp.type.variable", {})
vim.api.nvim_set_hl(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
vim.api.nvim_set_hl(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
vim.api.nvim_set_hl(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
vim.api.nvim_set_hl(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
vim.api.nvim_set_hl(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
vim.api.nvim_set_hl(0, "@lsp.typemod.keyword.injected", { link = "Statement" })
vim.api.nvim_set_hl(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
vim.api.nvim_set_hl(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
vim.api.nvim_set_hl(0, "@lsp.typemod.operator.injected", { link = "@operator" })
vim.api.nvim_set_hl(0, "@lsp.typemod.string.injected", { link = "@string" })
vim.api.nvim_set_hl(0, "@lsp.typemod.struct.defaultLibrary", { link = "@type.builtin" })
vim.api.nvim_set_hl(0, "@lsp.typemod.type.defaultLibrary", { link = "@type" })
vim.api.nvim_set_hl(0, "@lsp.typemod.typeAlias.defaultLibrary", { link = "@type" })
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.callable", { link = "@function" })
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.injected", { link = "@variable" })
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.static", { link = "@constant" })
vim.api.nvim_set_hl(0, "@markup.environment", { link = "PreProc" })
vim.api.nvim_set_hl(0, "@markup.heading", { link = "Title" })
vim.api.nvim_set_hl(0, "@markup.italic", { link = "Italic" })
vim.api.nvim_set_hl(0, "@markup.italic.markdown", { link = "Italic" })
vim.api.nvim_set_hl(0, "@markup.link", { link = "Constant" })
vim.api.nvim_set_hl(0, "@markup.link.label", { link = "Special" })
vim.api.nvim_set_hl(0, "@markup.link.markdown", { fg = "#84715F", underline = true })
vim.api.nvim_set_hl(0, "@markup.link.url", { link = "Constant" })
vim.api.nvim_set_hl(0, "@markup.link.url.markdown", { link = "SpecialComment" })
vim.api.nvim_set_hl(0, "@markup.link.vimdoc", { fg = "#84715F", underline = true })
vim.api.nvim_set_hl(0, "@markup.list", { link = "Special" })
vim.api.nvim_set_hl(0, "@markup.list.checked", { link = "@markup.list" })
vim.api.nvim_set_hl(0, "@markup.list.unchecked", { link = "@markup.list" })
vim.api.nvim_set_hl(0, "@markup.math", { link = "Special" })
vim.api.nvim_set_hl(0, "@markup.quote", { fg = "#95806C" })
vim.api.nvim_set_hl(0, "@markup.raw", { link = "Constant" })
vim.api.nvim_set_hl(0, "@markup.raw.block", { link = "@markup.raw" })
vim.api.nvim_set_hl(0, "@markup.raw.block.vimdoc", { fg = "NONE" })
vim.api.nvim_set_hl(0, "@markup.raw.markdown", { link = "Type" })
vim.api.nvim_set_hl(0, "@markup.strikethrough", { strikethrough = true })
vim.api.nvim_set_hl(0, "@markup.strong", { link = "Bold" })
vim.api.nvim_set_hl(0, "@markup.title.markdown", { link = "Statement" })
vim.api.nvim_set_hl(0, "@markup.underline", { link = "Underlined" })
vim.api.nvim_set_hl(0, "@module", { link = "Constant" })
vim.api.nvim_set_hl(0, "@module.builtin", { link = "@module" })
vim.api.nvim_set_hl(0, "@none", {})
vim.api.nvim_set_hl(0, "@number", { link = "Number" })
vim.api.nvim_set_hl(0, "@number.float", { link = "@number" })
vim.api.nvim_set_hl(0, "@operator", { link = "Statement" })
vim.api.nvim_set_hl(0, "@property", { link = "Identifier" })
vim.api.nvim_set_hl(0, "@punctuation.bracket", { link = "Delimiter" })
vim.api.nvim_set_hl(0, "@punctuation.delimiter", { link = "Delimiter" })
vim.api.nvim_set_hl(0, "@punctuation.special", { link = "Delimiter" })
vim.api.nvim_set_hl(0, "@punctuation.special.markdown", { link = "Special" })
vim.api.nvim_set_hl(0, "@string", { link = "String" })
vim.api.nvim_set_hl(0, "@string.documentation", { link = "@string" })
vim.api.nvim_set_hl(0, "@string.escape", { link = "Special" })
vim.api.nvim_set_hl(0, "@string.escape.markdown", { link = "SpecialKey" })
vim.api.nvim_set_hl(0, "@string.regexp", { link = "Constant" })
vim.api.nvim_set_hl(0, "@string.special", { link = "Special" })
vim.api.nvim_set_hl(0, "@string.special.path", { link = "@string.special" })
vim.api.nvim_set_hl(0, "@string.special.symbol", { link = "Identifier" })
vim.api.nvim_set_hl(0, "@string.special.url", { link = "@string.special" })
vim.api.nvim_set_hl(0, "@tag", { link = "Special" })
vim.api.nvim_set_hl(0, "@tag.attribute", { link = "@property" })
vim.api.nvim_set_hl(0, "@tag.delimiter", { link = "Delimiter" })
vim.api.nvim_set_hl(0, "@type", { link = "Type" })
vim.api.nvim_set_hl(0, "@type.builtin", { link = "@type" })
vim.api.nvim_set_hl(0, "@type.definition", { link = "@type" })
vim.api.nvim_set_hl(0, "@type.qualifier", { link = "@type" })
vim.api.nvim_set_hl(0, "@variable", { link = "Identifier" })
vim.api.nvim_set_hl(0, "@variable.builtin", { link = "Constant" })
vim.api.nvim_set_hl(0, "@variable.member", { link = "@variable" })
vim.api.nvim_set_hl(0, "@variable.parameter", { link = "@variable" })
vim.api.nvim_set_hl(0, "@variable.parameter.vimdoc", { link = "Type" })
vim.api.nvim_set_hl(0, "BlinkCmpKind", { bg = "#6B5C4D", fg = "#F4F0ED" })
vim.api.nvim_set_hl(0, "BlinkCmpLabelDescription", { link = "Type" })
vim.api.nvim_set_hl(0, "BlinkCmpLabelDetail", { link = "Type" })
vim.api.nvim_set_hl(0, "BlinkCmpSource", { link = "Type" })
vim.api.nvim_set_hl(0, "Bold", { bold = true })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#6B5C4D", italic = true })
vim.api.nvim_set_hl(0, "BufferCurrent", { link = "TabLineSel" })
vim.api.nvim_set_hl(0, "BufferVisible", { fg = "#9A8570" })
vim.api.nvim_set_hl(0, "BufferVisibleIndex", { fg = "#9A8570" })
vim.api.nvim_set_hl(0, "BufferVisibleSign", { fg = "#9A8570" })
vim.api.nvim_set_hl(0, "Character", { link = "Constant" })
vim.api.nvim_set_hl(0, "CmpItemAbbr", { fg = "#84715F" })
vim.api.nvim_set_hl(0, "CmpItemAbbrDeprecated", { fg = "#B29A82" })
vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", { bold = true, fg = "#6B5C4D" })
vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#7E6C5B" })
vim.api.nvim_set_hl(0, "CmpItemKind", { fg = "#95806C" })
vim.api.nvim_set_hl(0, "CmpItemMenu", { fg = "#A08A75" })
vim.api.nvim_set_hl(0, "CocCodeLens", { link = "LineNr" })
vim.api.nvim_set_hl(0, "CocErrorHighlight", { link = "DiagnosticUnderlineError" })
vim.api.nvim_set_hl(0, "CocErrorSign", { link = "DiagnosticSignError" })
vim.api.nvim_set_hl(0, "CocErrorVirtualText", { link = "DiagnosticVirtualTextError" })
vim.api.nvim_set_hl(0, "CocHintHighlight", { link = "DiagnosticUnderlineHint" })
vim.api.nvim_set_hl(0, "CocHintSign", { link = "DiagnosticSignHint" })
vim.api.nvim_set_hl(0, "CocInfoHighlight", { link = "DiagnosticUnderlineInfo" })
vim.api.nvim_set_hl(0, "CocInfoSign", { link = "DiagnosticSignInfo" })
vim.api.nvim_set_hl(0, "CocMarkdownLink", { fg = "#83B887", underline = true })
vim.api.nvim_set_hl(0, "CocMenuSel", { link = "CursorLine" })
vim.api.nvim_set_hl(0, "CocSearch", { link = "Search" })
vim.api.nvim_set_hl(0, "CocSelectedText", { link = "SpellBad" })
vim.api.nvim_set_hl(0, "CocWarningHighlight", { link = "DiagnosticUnderlineWarn" })
vim.api.nvim_set_hl(0, "CocWarningSign", { link = "DiagnosticSignWarn" })
vim.api.nvim_set_hl(0, "CocWarningVirtualText", { link = "DiagnosticVirtualTextWarn" })
vim.api.nvim_set_hl(0, "ColorColumn", { bg = "#E8CB9B" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#988C81", italic = true })
vim.api.nvim_set_hl(0, "Conceal", { bold = true, fg = "#A08A75", italic = true })
vim.api.nvim_set_hl(0, "Constant", { fg = "#95806C", italic = true })
vim.api.nvim_set_hl(0, "CurSearch", { link = "IncSearch" })
vim.api.nvim_set_hl(0, "Cursor", { bg = "#6B5C4D", fg = "#F4F0ED" })
vim.api.nvim_set_hl(0, "CursorColumn", { link = "CursorLine" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#E9E1DB" })
vim.api.nvim_set_hl(0, "CursorLineNr", { bg = "NONE", bold = true, fg = "#6B5C4D" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#918173" })
vim.api.nvim_set_hl(0, "DiagnosticDeprecated", { link = "DiagnosticWarn" })
vim.api.nvim_set_hl(0, "DiagnosticError", { link = "Error" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#D7898C" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#485F84" })
vim.api.nvim_set_hl(0, "DiagnosticOk", { fg = "#659E69" })
vim.api.nvim_set_hl(0, "DiagnosticSignError", { bg = "NONE", fg = "#C65333" })
vim.api.nvim_set_hl(0, "DiagnosticSignHint", { bg = "NONE", fg = "#D7898C" })
vim.api.nvim_set_hl(0, "DiagnosticSignInfo", { bg = "NONE", fg = "#485F84" })
vim.api.nvim_set_hl(0, "DiagnosticSignOk", { bg = "NONE", fg = "#659E69" })
vim.api.nvim_set_hl(0, "DiagnosticSignWarn", { bg = "NONE", fg = "#C29830" })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { fg = "NONE", sp = "#C65333", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { fg = "NONE", sp = "#D7898C", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { fg = "NONE", sp = "#485F84", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineOk", { fg = "NONE", sp = "#659E69", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { fg = "NONE", sp = "#C29830", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnnecessary", { link = "DiagnosticWarn" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { bg = "#F1E2E0", fg = "#C65333" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", { bg = "#F1E2E2", fg = "#D7898C" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", { bg = "#E0E5F0", fg = "#485F84" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextOk", { bg = "#C2F1C5", fg = "#659E69" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", { bg = "#F1E3D1", fg = "#C29830" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { link = "WarningMsg" })
vim.api.nvim_set_hl(0, "DiffAdd", { bg = "#BFEBC2" })
vim.api.nvim_set_hl(0, "DiffChange", { bg = "#DBE0E9" })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = "#EDDCDA" })
vim.api.nvim_set_hl(0, "DiffText", { bg = "#B5BFD2", fg = "#6B5C4D" })
vim.api.nvim_set_hl(0, "Directory", { bold = true })
vim.api.nvim_set_hl(0, "EndOfBuffer", { link = "NonText" })
vim.api.nvim_set_hl(0, "Error", { fg = "#C65333" })
vim.api.nvim_set_hl(0, "ErrorMsg", { link = "Error" })
vim.api.nvim_set_hl(0, "FlashBackdrop", { fg = "#988C81" })
vim.api.nvim_set_hl(0, "FlashLabel", { bg = "#B9C7E3", fg = "#6B5C4D" })
vim.api.nvim_set_hl(0, "Float", { link = "Number" })
vim.api.nvim_set_hl(0, "FloatBorder", { bg = "NONE", fg = "#7D7064" })
vim.api.nvim_set_hl(0, "FloatTitle", { bg = "#E3D8CF", bold = true, fg = "#6B5C4D" })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = "NONE", bold = true, fg = "#AA9888" })
vim.api.nvim_set_hl(0, "Folded", { bg = "#D6C3B4", fg = "#584E45" })
vim.api.nvim_set_hl(0, "Function", { fg = "#6B5C4D" })
vim.api.nvim_set_hl(0, "FzfLuaBufFlagAlt", { fg = "#485F84" })
vim.api.nvim_set_hl(0, "FzfLuaBufFlagCur", { fg = "#C29830" })
vim.api.nvim_set_hl(0, "FzfLuaBufName", { link = "Statement" })
vim.api.nvim_set_hl(0, "FzfLuaBufNr", { fg = "#659E69" })
vim.api.nvim_set_hl(0, "FzfLuaFzfCursorLine", { link = "CursorLine" })
vim.api.nvim_set_hl(0, "FzfLuaFzfMatch", { bold = true, fg = "#D7898C" })
vim.api.nvim_set_hl(0, "FzfLuaHeaderBind", { fg = "#659E69" })
vim.api.nvim_set_hl(0, "FzfLuaHeaderText", { fg = "#C29830" })
vim.api.nvim_set_hl(0, "FzfLuaLiveSym", { fg = "#C29830" })
vim.api.nvim_set_hl(0, "FzfLuaPathColNr", { bold = true, fg = "#695645" })
vim.api.nvim_set_hl(0, "FzfLuaPathLineNr", { link = "FzfLuaPathColNr" })
vim.api.nvim_set_hl(0, "FzfLuaTabMarker", { fg = "#659E69" })
vim.api.nvim_set_hl(0, "FzfLuaTabTitle", { fg = "#83B887" })
vim.api.nvim_set_hl(0, "FzfLuaTitle", { link = "Title" })
vim.api.nvim_set_hl(0, "GitGutterAdd", { link = "GitSignsAdd" })
vim.api.nvim_set_hl(0, "GitGutterChange", { link = "GitSignsChange" })
vim.api.nvim_set_hl(0, "GitGutterDelete", { link = "GitSignsDelete" })
vim.api.nvim_set_hl(0, "GitSignsAdd", { bg = "NONE", fg = "#659E69" })
vim.api.nvim_set_hl(0, "GitSignsChange", { bg = "NONE", fg = "#485F84" })
vim.api.nvim_set_hl(0, "GitSignsDelete", { bg = "NONE", fg = "#C65333" })
vim.api.nvim_set_hl(0, "HopNextKey", { bold = true, fg = "#D7898C", underline = true })
vim.api.nvim_set_hl(0, "HopNextKey1", { bold = true, fg = "#83B887", underline = true })
vim.api.nvim_set_hl(0, "HopNextKey2", { fg = "#485F84" })
vim.api.nvim_set_hl(0, "HopUnmatched", { fg = "#988C81" })
vim.api.nvim_set_hl(0, "IblIndent", { fg = "#E6DED8" })
vim.api.nvim_set_hl(0, "IblScope", { fg = "#C5B3A4" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#84715F" })
vim.api.nvim_set_hl(0, "IncSearch", { bg = "#D3767A", bold = true, fg = "#F4F0ED" })
vim.api.nvim_set_hl(0, "IndentLine", { link = "IblIndent" })
vim.api.nvim_set_hl(0, "IndentLineCurrent", { link = "IblScope" })
vim.api.nvim_set_hl(0, "Italic", { italic = true })
vim.api.nvim_set_hl(0, "LeapBackdrop", { fg = "#CBB5A2", nocombine = true })
vim.api.nvim_set_hl(0, "LeapLabel", { bold = true, fg = "#E22237" })
vim.api.nvim_set_hl(0, "LeapMatch", { bold = true, nocombine = true, underline = true })
vim.api.nvim_set_hl(0, "LineNr", { bg = "NONE", fg = "#AA9888" })
vim.api.nvim_set_hl(0, "LspCodeLens", { link = "LineNr" })
vim.api.nvim_set_hl(0, "LspInlayHint", { bg = "#F0EAE6", fg = "#A68F7A" })
vim.api.nvim_set_hl(0, "LspReferenceRead", { link = "ColorColumn" })
vim.api.nvim_set_hl(0, "LspReferenceText", { link = "ColorColumn" })
vim.api.nvim_set_hl(0, "LspReferenceWrite", { link = "ColorColumn" })
vim.api.nvim_set_hl(0, "MasonError", { link = "Error" })
vim.api.nvim_set_hl(0, "MasonHeader", { bg = "#C29830", bold = true, fg = "#F4F0ED" })
vim.api.nvim_set_hl(0, "MasonHighlight", { fg = "#485F84" })
vim.api.nvim_set_hl(0, "MasonHighlightBlock", { bg = "#485F84", fg = "#F4F0ED" })
vim.api.nvim_set_hl(0, "MasonHighlightBlockBold", { bg = "#485F84", bold = true, fg = "#F4F0ED" })
vim.api.nvim_set_hl(0, "MasonHighlightBlockBoldSecondary", { bg = "#C29830", bold = true, fg = "#F4F0ED" })
vim.api.nvim_set_hl(0, "MasonHighlightBlockSecondary", { bg = "#C29830", fg = "#F4F0ED" })
vim.api.nvim_set_hl(0, "MasonHighlightSecondary", { fg = "#C29830" })
vim.api.nvim_set_hl(0, "MasonMuted", { fg = "#95806C" })
vim.api.nvim_set_hl(0, "MasonMutedBlock", { bg = "#95806C", fg = "#F4F0ED" })
vim.api.nvim_set_hl(0, "MasonMutedBlockBold", { bg = "#95806C", bold = true, fg = "#F4F0ED" })
vim.api.nvim_set_hl(0, "MatchParen", { bold = true })
vim.api.nvim_set_hl(0, "ModeMsg", { link = "Normal" })
vim.api.nvim_set_hl(0, "MoreMsg", { bold = true, fg = "#659E69" })
vim.api.nvim_set_hl(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
vim.api.nvim_set_hl(0, "NeogitDiffContextHighlight", { link = "CursorLine" })
vim.api.nvim_set_hl(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
vim.api.nvim_set_hl(0, "NeogitHunkHeader", { link = "LineNr" })
vim.api.nvim_set_hl(0, "NeogitHunkHeaderHighlight", { bg = "#E9E1DB", bold = true, fg = "#6B5C4D" })
vim.api.nvim_set_hl(0, "NeogitNotificationError", { link = "DiagnosticError" })
vim.api.nvim_set_hl(0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
vim.api.nvim_set_hl(0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
vim.api.nvim_set_hl(0, "NnnNormal", { link = "NvimTreeNormal" })
vim.api.nvim_set_hl(0, "NnnNormalNC", { link = "NnnNormal" })
vim.api.nvim_set_hl(0, "NnnVertSplit", { link = "NnnWinSeparator" })
vim.api.nvim_set_hl(0, "NnnWinSeparator", { link = "NvimTreeWinSeparator" })
vim.api.nvim_set_hl(0, "NoiceCmdlineIcon", { fg = "#485F84" })
vim.api.nvim_set_hl(0, "NoiceCmdlineIconSearch", { link = "WarningMsg" })
vim.api.nvim_set_hl(0, "NoiceCmdlinePopupBorder", { link = "NoiceCmdlineIcon" })
vim.api.nvim_set_hl(0, "NoiceCmdlinePopupBorderSearch", { link = "WarningMsg" })
vim.api.nvim_set_hl(0, "NoiceCmdlinePopupTitle", { link = "NoiceCmdlineIcon" })
vim.api.nvim_set_hl(0, "NoiceCompletionItemKindDefault", { fg = "#95806C" })
vim.api.nvim_set_hl(0, "NoiceConfirmBorder", { link = "NoiceCmdlineIcon" })
vim.api.nvim_set_hl(0, "NonText", { fg = "#BFAA99" })
vim.api.nvim_set_hl(0, "Normal", { bg = "#F4F0ED", fg = "#6B5C4D" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "#E3D8CF" })
vim.api.nvim_set_hl(0, "NotifyDEBUGIcon", { link = "DiagnosticHint" })
vim.api.nvim_set_hl(0, "NotifyDEBUGTitle", { link = "DiagnosticHint" })
vim.api.nvim_set_hl(0, "NotifyERRORIcon", { link = "DiagnosticError" })
vim.api.nvim_set_hl(0, "NotifyERRORTitle", { link = "DiagnosticError" })
vim.api.nvim_set_hl(0, "NotifyINFOIcon", { link = "DiagnosticInfo" })
vim.api.nvim_set_hl(0, "NotifyINFOTitle", { link = "DiagnosticInfo" })
vim.api.nvim_set_hl(0, "NotifyTRACEIcon", { link = "DiagnosticHint" })
vim.api.nvim_set_hl(0, "NotifyTRACETitle", { link = "DiagnosticHint" })
vim.api.nvim_set_hl(0, "NotifyWARNIcon", { link = "DiagnosticWarn" })
vim.api.nvim_set_hl(0, "NotifyWARNTitle", { link = "DiagnosticWarn" })
vim.api.nvim_set_hl(0, "Number", { fg = "#95806C" })
vim.api.nvim_set_hl(0, "NvimTreeCursorColumn", { link = "NvimTreeCursorLine" })
vim.api.nvim_set_hl(0, "NvimTreeCursorLine", { bg = "#E7DED7" })
vim.api.nvim_set_hl(0, "NvimTreeGitDeleted", { link = "diffRemoved" })
vim.api.nvim_set_hl(0, "NvimTreeGitDirty", { link = "diffChanged" })
vim.api.nvim_set_hl(0, "NvimTreeGitNew", { link = "diffAdded" })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { bg = "#EDE7E2", fg = "#6B5C4D" })
vim.api.nvim_set_hl(0, "NvimTreeRootFolder", { bold = true, fg = "#485F84" })
vim.api.nvim_set_hl(0, "NvimTreeSpecialFile", { fg = "#D7898C", underline = true })
vim.api.nvim_set_hl(0, "NvimTreeSymlink", { fg = "#485F84" })
vim.api.nvim_set_hl(0, "NvimTreeWinSeparator", { fg = "bg" })
vim.api.nvim_set_hl(0, "Pmenu", { bg = "#E1D5CB" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#B6A292" })
vim.api.nvim_set_hl(0, "PmenuSel", { bg = "#CEB8A5" })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#FBF9F8" })
vim.api.nvim_set_hl(0, "PreProc", { link = "Statement" })
vim.api.nvim_set_hl(0, "Question", { link = "MoreMsg" })
vim.api.nvim_set_hl(0, "QuickFixLine", { link = "Search" })
vim.api.nvim_set_hl(0, "RenderMarkdownCode", { bg = "#F0EAE6" })
vim.api.nvim_set_hl(0, "Search", { bg = "#E5BDBE", fg = "#6B5C4D" })
vim.api.nvim_set_hl(0, "SignColumn", { link = "LineNr" })
vim.api.nvim_set_hl(0, "SnacksIndent", { fg = "#E6DED8" })
vim.api.nvim_set_hl(0, "SnacksIndentScope", { fg = "#C5B3A4" })
vim.api.nvim_set_hl(0, "SnacksPickerBorder", { link = "NormalFloat" })
vim.api.nvim_set_hl(0, "SnacksPickerListCursorLine", { link = "CursorLine" })
vim.api.nvim_set_hl(0, "SnacksPickerMatch", { bold = true, fg = "#D7898C" })
vim.api.nvim_set_hl(0, "SnacksPickerPreviewCursorLine", { link = "CursorLine" })
vim.api.nvim_set_hl(0, "Sneak", { link = "Search" })
vim.api.nvim_set_hl(0, "SneakLabel", { link = "WildMenu" })
vim.api.nvim_set_hl(0, "SneakLabelMask", { bg = "#D7898C", fg = "#D7898C" })
vim.api.nvim_set_hl(0, "Special", { bold = true, fg = "#8F7B68" })
vim.api.nvim_set_hl(0, "SpecialComment", { fg = "#988C81" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#BFAA99", italic = true })
vim.api.nvim_set_hl(0, "SpellBad", { fg = "#B45F4E", sp = "#C65333", undercurl = true })
vim.api.nvim_set_hl(0, "SpellCap", { fg = "#B45F4E", sp = "#DA5C39", undercurl = true })
vim.api.nvim_set_hl(0, "SpellLocal", { link = "SpellCap" })
vim.api.nvim_set_hl(0, "SpellRare", { fg = "#B45F4E", sp = "#C29830", undercurl = true })
vim.api.nvim_set_hl(0, "Statement", { bold = true, fg = "#6B5C4D" })
vim.api.nvim_set_hl(0, "StatusLine", { bg = "#DDCFC4", fg = "#6B5C4D" })
vim.api.nvim_set_hl(0, "StatusLineNC", { bg = "#E7DED7", fg = "#9A8570" })
vim.api.nvim_set_hl(0, "String", { fg = "#95806C", italic = true })
vim.api.nvim_set_hl(0, "TabLine", { link = "StatusLine" })
vim.api.nvim_set_hl(0, "TabLineFill", { link = "StatusLineNC" })
vim.api.nvim_set_hl(0, "TabLineSel", { bold = true })
vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = "#7D7064" })
vim.api.nvim_set_hl(0, "TelescopeMatching", { bold = true, fg = "#D7898C" })
vim.api.nvim_set_hl(0, "TelescopeSelection", { link = "CursorLine" })
vim.api.nvim_set_hl(0, "TelescopeSelectionCaret", { bg = "#E9E1DB", fg = "#C65333" })
vim.api.nvim_set_hl(0, "TermCursor", { link = "Cursor" })
vim.api.nvim_set_hl(0, "TermCursorNC", { link = "lCursor" })
vim.api.nvim_set_hl(0, "Title", { bold = true, fg = "#6B5C4D" })
vim.api.nvim_set_hl(0, "Todo", { bold = true, underline = true })
vim.api.nvim_set_hl(0, "TroubleNormal", { link = "Function" })
vim.api.nvim_set_hl(0, "TroubleSource", { link = "Constant" })
vim.api.nvim_set_hl(0, "TroubleText", { link = "Function" })
vim.api.nvim_set_hl(0, "Type", { fg = "#695645" })
vim.api.nvim_set_hl(0, "Underlined", { underline = true })
vim.api.nvim_set_hl(0, "VertSplit", { link = "WinSeparator" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#E7D7CA" })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#C29830" })
vim.api.nvim_set_hl(0, "WhichKey", { link = "Statement" })
vim.api.nvim_set_hl(0, "WhichKeyGroup", { link = "Special" })
vim.api.nvim_set_hl(0, "WhichKeySeparator", { fg = "#AA9888" })
vim.api.nvim_set_hl(0, "WhichKeyValue", { link = "Constant" })
vim.api.nvim_set_hl(0, "Whitespace", { link = "NonText" })
vim.api.nvim_set_hl(0, "WildMenu", { bg = "#D7898C", fg = "#F4F0ED" })
vim.api.nvim_set_hl(0, "WinBar", { link = "StatusLine" })
vim.api.nvim_set_hl(0, "WinBarNC", { link = "StatusLineNC" })
vim.api.nvim_set_hl(0, "WinSeparator", { bg = "NONE", fg = "#AA9888" })
vim.api.nvim_set_hl(0, "diffAdded", { link = "DiffAdd" })
vim.api.nvim_set_hl(0, "diffChanged", { link = "DiffChange" })
vim.api.nvim_set_hl(0, "diffFile", { bold = true, fg = "#C29830" })
vim.api.nvim_set_hl(0, "diffIndexLine", { fg = "#C29830" })
vim.api.nvim_set_hl(0, "diffLine", { bold = true, fg = "#D7898C" })
vim.api.nvim_set_hl(0, "diffNewFile", { fg = "#659E69", italic = true })
vim.api.nvim_set_hl(0, "diffOldFile", { fg = "#C65333", italic = true })
vim.api.nvim_set_hl(0, "diffRemoved", { link = "DiffDelete" })
vim.api.nvim_set_hl(0, "gitcommitOverflow", { link = "WarningMsg" })
vim.api.nvim_set_hl(0, "helpHyperTextEntry", { bold = true, fg = "#695645" })
vim.api.nvim_set_hl(0, "helpHyperTextJump", { fg = "#84715F", underline = true })
vim.api.nvim_set_hl(0, "helpOption", { link = "Constant" })
vim.api.nvim_set_hl(0, "helpSpecial", { link = "Type" })
vim.api.nvim_set_hl(0, "lCursor", { bg = "#8C7966", fg = "#F4F0ED" })
vim.api.nvim_set_hl(0, "markdownCode", { link = "Type" })
vim.api.nvim_set_hl(0, "markdownLinkText", { fg = "#84715F", underline = true })
vim.api.nvim_set_hl(0, "markdownLinkTextDelimiter", { link = "Delimiter" })
vim.api.nvim_set_hl(0, "markdownUrl", { link = "SpecialComment" })
